services:
  db:
    image: ghcr.io/railwayapp-templates/postgres-ssl:18
    container_name: trana-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trana
      POSTGRES_PASSWORD: trana1234
      POSTGRES_DB: trana
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
